/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csg;

/**
 *
 * @author hanli
 */
public enum CourseSiteGeneratorPropertyType {
    
    // Tab
        CSG_SITE_TAB, CSG_SYLLABUS_TAB, CSG_MEETING_TIME_TAB, CSG_OH_TAB, CSG_SCHEDULE_TAB,
        CSG_SITE_PANE, CSG_SYLLABUS_PANE, CSG_MEETING_TIME_PANE, CSG_OH_PANE, CSG_SCHEDULE_PANE,
        //Banner
        CSG_SITE_BANNER_PANE,
        CSG_SITE_BANNER_LABEL, CSG_SITE_SUBJECT_LABEL, CSG_SITE_SUBJECT_CB,
        CSG_SITE_NUMBER_CB, CSG_SITE_NUMBER_LABEL, CSG_SITE_SEMESTER_CB,
        CSG_SITE_SEMESTER_LABEL, CSG_SITE_YEAR_LABEL,
        CSG_SITE_YEAR_CB, CSG_SITE_TITLE_TF, CSG_SITE_TITLE_LABEL,
        CSG_SITE_EXPORT_DIR_LABEL, CSG_SITE_DIR_LABEL,
    //Pages    
        CSG_SITE_PAGES_PANE, CSG_SITE_PAGES_LABEL,
        CSG_SITE_HOME_CB,
        CSG_SITE_SYLLABUS_CB, CSG_SITE_SCHEDULE_CB,
        CSG_SITE_HWS_CB, 
     // Style   
        CSG_SITE_STYLE_PANE,
        CSG_SITE_STYLE_LABEL, CSG_SITE_FAVICON_BUTTON,
        CSG_SITE_FAVICON_IMAGE, CSG_SITE_NAVBAR_BUTTON,
        CSG_SITE_NAVBAR_IMAGE, CSG_SITE_LEFT_FOOTER_BUTTON,
        CSG_SITE_LEFT_FOOTER_IMAGE, CSG_SITE_RIGHT_FOOTER_BUTTON,
        CSG_SITE_RIGHT_FOOTER_IMAGE, CSG_SITE_STYLESHEET_CB,
        CSG_SITE_STYLESHEET_LABEL, CSG_SITE_STYLESHEET_NOTE_LABEL,
    // Instructor  
        CSG_SITE_INSTRUCTOR_PANE, CSG_SITE_INSTRUCTORINFO_PANE, CSG_SITE_INSTRUCTOR_LABEL,
        CSG_SITE_NAME_LABEL, CSG_SITE_ROOM_LABEL,
        CSG_SITE_EMAIL_LABEL, CSG_SITE_HOMEPAGE_LABEL,
        CSG_SITE_NAME_TF, CSG_SITE_ROOM_TF,
        CSG_SITE_EMAIL_TF, CSG_SITE_HOMEPAGE_TF,
        CSG_SITE_OH_TITLEDPANE, CSG_SITE_OH_TA, 
     //Syllabus TAB
        CSG_SYLLABUS_DESCRIPTION_TP,
        CSG_SYLLABUS_TOPICS_TP, CSG_SYLLABUS_PREREQUISITES_TP,
        CSG_SYLLABUS_OUTCOMES_TP, CSG_SYLLABUS_TEXTBOOKS_TP,
        CSG_SYLLABUS_GRADED_COMPONENTS_TP, CSG_SYLLABUS_GRADING_NOTE_TP,
        CSG_SYLLABUS_ACADEMIC_DISHONESTY_TP, CSG_SYLLABUS_SPECIAL_ASSISTANCE_TP,
        CSG_SYLLABUS_DESCRIPTION_TA,
        CSG_SYLLABUS_TOPICS_TA, CSG_SYLLABUS_PREREQUISITES_TA,
        CSG_SYLLABUS_OUTCOMES_TA, CSG_SYLLABUS_TEXTBOOKS_TA,
        CSG_SYLLABUS_GRADED_COMPONENTS_TA, CSG_SYLLABUS_GRADING_NOTE_TA,
        CSG_SYLLABUS_ACADEMIC_DISHONESTY_TA, CSG_SYLLABUS_SPECIAL_ASSISTANCE_TA,
     //Meeting Times TAB
        CSG_LECTURES_PANE, CSG_LECTURES_HEADER_PANE, 
        CSG_LECTURES_ADD_BT, CSG_LECTURES_REMOVE_BT, CSG_LECTURES_LABEL,
        CSG_LECTURES_TABLEVIEW,
        CSG_LECTURES_SECTION_TABLE_COLUMN, CSG_LECTURES_DAYS_TABLE_COLUMN,
        CSG_LECTURES_TIME_TABLE_COLUMN, CSG_LECTURES_ROOM_TABLE_COLUMN, 
        CSG_REC_PANE, CSG_REC_HEADER_PANE, CSG_REC_TABLEVIEW,
        CSG_REC_ADD_BT, CSG_REC_REMOVE_BT, CSG_REC_LABEL,
        CSG_REC_SECTION_TABLE_COLUMN, CSG_REC_DAYSTIME_TABLE_COLUMN,
        CSG_REC_ROOM_TABLE_COLUMN, CSG_REC_TA1_TABLE_COLUMN, 
        CSG_REC_TA2_TABLE_COLUMN, 
        CSG_LABS_PANE, CSG_LABS_HEADER_PANE, CSG_LABS_LABEL, 
        CSG_LABS_ADD_BT, CSG_LABS_REMOVE_BT,  CSG_LABS_TABLEVIEW,
        CSG_LABS_SECTION_TABLE_COLUMN, CSG_LABS_DAYSTIME_TABLE_COLUMN,
        CSG_LABS_ROOM_TABLE_COLUMN, CSG_LABS_TA1_TABLE_COLUMN, 
        CSG_LABS_TA2_TABLE_COLUMN, 
        
        CSG_OK_PROMPT, CSG_CANCEL_PROMPT,
     // Office Hours TAB
        // TA
        CSG_OH_TAS_PANE, CSG_OH_TAS_HEADER_PANE, CSG_OH_TAS_REMOVE_BT,
        CSG_OH_TAS_LABEL,
        CSG_OH_TAS_ALL_RB, CSG_OH_TAS_GRAD_RB,
        CSG_OH_TAS_UNDERGRA_RB, CSG_OH_TAS_TABLE_VIEW,
        CSG_OH_TAS_NAME_TABLE_COLUMN, CSG_OH_TAS_EMAIL_TABLE_COLUMN,
        CSG_OH_TAS_SLOTS_TABLE_COLUMN, CSG_OH_TAS_TYPE_TABLE_COLUMN,
        CSG_OH_TAS_ADD_TA_PANE, CSG_OH_TAS_NAME_TEXT_FIELD,
        CSG_OH_TAS_EMAIL_TEXT_FIELD, CSG_OH_TAS_ADD_TA_BUTTON,
        // OH
        CSG_OH_OHS_PANE, CSG_OH_HEADER_PANE,
        CSG_OH_LABEL, CSG_OH_START_TIME_LABEL, CSG_OH_END_TIME_LABEL,
        CSG_OH_START_TIME_CB, CSG_OH_END_TIME_CB, CSG_OH_TABLEVIEW,
        CSG_START_TIME_TABLE_COLUMN, CSG_END_TIME_TABLE_COLUMN,
        CSG_MONDAY_TABLE_COLUMN, CSG_TUESDAY_TABLE_COLUMN,
        CSG_WEDNESDAY_TABLE_COLUMN, CSG_THURSDAY_TABLE_COLUMN,
        CSG_FRIDAY_TABLE_COLUMN,
      // TA EDIT DIALOGS
        CSG_EDIT_DIALOG_TITLE, CSG_EDIT_DIALOG_NAME, CSG_EDIT_DIALOG_NAME_PROMPT,
        CSG_EDIT_DIALOG_EMAIL, CSG_EDIT_DIALOG_EMAIL_PROMPT, CSG_EDIT_DIALOG_TYPE,
        CSG_EDIT_DIALOG_GRADUATE,
        CSG_EDIT_DIALOG_UNDERGRADUATE,
        
        CSG_FOOLPROOF_SETTINGS, 
        
        // Schedule TAB
        CSG_SCHEDULE_BOUNDARIES_PANE, 
        CSG_SCHEDULE_STARTING_MONDAY_DP, CSG_SCHEDULE_STARTING_MONDAY_LABEL,
        CSG_SCHEDULE_ENDING_FRIDAY_DP, CSG_SCHEDULE_ENDING_FRIDAY_LABEL, 
        CSG_SCHEDULE_ADD_ITEM_BT,
        CSG_SCHEDULE_REMOVE_ITEM_BT, CSG_SCHEDULE_CLEAR_ITEM_BT,
        CSG_SCHEDULE_TABLEVIEW, CSG_SCHEDULE_TYPE_TABLE_COLUMN, 
        CSG_SCHEDULE_DATE_TABLE_COLUMN, CSG_SCHEDULE_TITLE_TABLE_COLUMN,
        CSG_SCHEDULE_TOPIC_TABLE_COLUMN, CSG_SCHEDULE_TYPE_CB,
        CSG_SCHEDULE_DATE_DP, CSG_SCHEDULE_TITLE_TF,
        CSG_SCHEDULE_TOPIC_TF, CSG_SCHEDULE_LINK_TF
}
