/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package csg;

/**
 *
 * @author hanli
 */
public enum CourseSiteGeneratorPropertyType {
    CSG_SITE_SUBJECT_CB,
CSG_SITE_NUMBER_CB, CSG_SITE_SEMESTER_CB,
CSG_SITE_YEAR_CB, CSG_SITE_TITLE_TF,
CSG_SITE_EXPORT_DIR_LBL, CSG_SITE_HOME_CB,
CSG_SITE_SYLLABUS_CB, CSG_SITE_SCHEDULE_CB,
CSG_SITE_HWS_CB, CSG_SITE_FAVICON_BUTTON,
CSG_SITE_FAVICON_IMAGE, CSG_SITE_NAVBAR_BUTTON,
CSG_SITE_NAVBAR_IMAGE, CSG_SITE_LEFT_FOOTER_BUTTON,
CSG_SITE_LEFT_FOOTER_IMAGE, CSG_SITE_RIGHT_FOOTER_BUTTON,
CSG_SITE_RIGHT_FOOTER_IMAGE, CDG_SITE_STYLESHEET_CB,
CSG_SITE_NAME_TF, CSG_SITE_ROOM_TF,
CSG_SITE_EMAIL_TF, CSG_SITE_HOMEPAGE_TF,
CSG_SITE_OH_TF, CSG_SYLLABUS_DESCRIPTION_TA,
CSG_SYLLABUS_TOPICS_TA, CSG_SYLLABUS_PREREQUISITES_TA,
CSG_SYLLABUS_OUTCOMES_TA, CSG_SYLLABUS_TEXTBOOKS_TA,
CSG_SYLLABUS_GRADED_TA, CSG_SYLLABUS_GRADING_NOTE_TA,
CSG_SYLLABUS_ACADEMIC_TA, CSG_SYLLABUS_SPECIAL_TA,
CSG_LECTURES_ADD_BT, CSG_LECTURES_REMOVE_BT,
CSG_LECTURES_SECTION_TABLE_COLUMN, CSG_LECTURES_DAYS_TABLE_COLUMN,
CSG_LECTURES_TIME_TABLE_COLUMN, CSG_LECTURES_ROOM_TABLE_COLUMN, 
CSG_REC_ADD_BT, CSG_REC_REMOVE_BT,
CSG_REC_SECTION_TABLE_COLUMN, CSG_REC_DAYSTIME_TABLE_COLUMN,
CSG_REC_ROOM_TABLE_COLUMN, CSG_REC_TA1_TABLE_COLUMN, 
CSG_REC_TA2_TABLE_COLUMN, CSG_LABS_ADD_BT, CSG_LABS_REMOVE_BT,
CSG_LABS_SECTION_TABLE_COLUMN, CSG_LABS_DAYSTIME_TABLE_COLUMN,
CSG_LABS_ROOM_TABLE_COLUMN, CSG_LABS_TA1_TABLE_COLUMN, 
CSG_LABS_TA2_TABLE_COLUMN, CSG_OK_PROMPT, CSG_CANCEL_PROMPT,
CSG_LEFT_PANE, CSG_TAS_HEADER_PANE,
CSG_TAS_HEADER_LABEL, CSG_TAS_HEADER_TEXT_FIELD,
CSG_TAS_ALL_RB, CSG_TAS_GRADUATE_RB,
CSG_TAS_UNDERGRADUATE_RB, CSG_TAS_TABLE_VIEW,
CSG_NAME_TABLE_COLUMN, CSG_EMAIL_TABLE_COLUMN,
CSG_SLOTS_TABLE_COLUMN, CSG_TYPE_TABLE_COLUMN,
CSG_ADD_TA_PANE, CSG_NAME_TEXT_FIELD,
CSG_EMAIL_TEXT_FIELD, CSG_ADD_TA_BUTTON,
CSG_RIGHT_PANE, CSG_OFFICE_HOURS_HEADER_PANE,
CSG_OFFICE_HOURS_HEADER_LABEL, CSG_OFFICE_HOURS_TABLE_VIEW,
CSG_START_TIME_TABLE_COLUMN, CSG_END_TIME_TABLE_COLUMN,
CSG_MONDAY_TABLE_COLUMN, CSG_TUESDAY_TABLE_COLUMN,
CSG_WEDNESDAY_TABLE_COLUMN, CSG_THURSDAY_TABLE_COLUMN,
CSG_FRIDAY_TABLE_COLUMN, CSG_DAYS_OF_WEEK,
CSG_FOOLPROOF_SETTINGS, CSG_SCHEDULE_STARTING_MONDAY_DP,
CSG_SCHEDULE_ENDING_FRIDAY_DP, CSG_SCHEDULE_ADD_ITEM_BT,
CSG_SCHEDULE_REMOVE_ITEM_BT, CSG_SCHEDULE_CLEAR_ITEM_BT,
CSG_SCHEDULE_TABLEVIEW, CSG_SCHEDULE_TYPE_TABLE_COLUMN, 
CSG_SCHEDULE_DATE_TABLE_COLUMN, CSG_SCHEDULE_TITLE_TABLE_COLUMN,
CSG_SCHEDULE_TOPIC_TABLE_COLUMN, CSG_SCHEDULE_TYPE_CB,
CSG_SCHEDULE_DATE_DP, CSG_SCHEDULE_TITLE_TF,
CSG_SCHEDULE_TOPIC_TF, CSG_SCHEDULE_LINK_TF
}
